# Generated by Django 6.0.2 on 2026-02-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_template', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_sentences', to='verbs.verb')),
            ],
            options={
                'verbose_name': 'Invulzin',
                'verbose_name_plural': 'Invulzinnen',
            },
        ),
    ]
