# Generated by Django 6.0.2 on 2026-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_add_fill_in_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillinsentence',
            name='answer_form_key',
            field=models.CharField(blank=True, choices=[('tt_ik', 'ik (tt)'), ('tt_jij', 'jij (tt)'), ('tt_hij', 'hij/zij (tt)'), ('vt_ev', 'hij/zij (vt)'), ('vt_mv', 'zij (vt mv)'), ('vd', 'voltooid deelwoord'), ('vd_hulpwerkwoord', 'hulpwerkwoord'), ('infinitive', 'Infinitief (heel werkwoord)')], default='', max_length=20),
        ),
    ]
