# Generated by Django 6.0.2 on 2026-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_add_answer_form_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinsentence',
            name='answer_form_key',
            field=models.CharField(blank=True, choices=[('tt_ik', 'ik (tt)'), ('tt_jij', 'jij (tt)'), ('tt_hij', 'hij/zij/het (tt)'), ('vt_ev', 'hij/zij/het (vt)'), ('vt_mv', 'wij/jullie/zij (vt mv)'), ('vd', 'voltooid deelwoord'), ('vd_hulpwerkwoord', 'hulpwerkwoord'), ('infinitive', 'Infinitief (heel werkwoord)')], default='', max_length=20),
        ),
    ]
